// This file is part of OpenTSDB.
// Copyright (C) 2010-2012  The OpenTSDB Authors.
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 2.1 of the License, or (at your
// option) any later version.  This program is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
// General Public License for more details.  You should have received a copy
// of the GNU Lesser General Public License along with this program.  If not,
// see <http://www.gnu.org/licenses/>.
package net.opentsdb.search;

import com.stumbleupon.async.Deferred;

import net.opentsdb.core.TSDB;
import net.opentsdb.meta.Annotation;
import net.opentsdb.meta.TSMeta;
import net.opentsdb.meta.UIDMeta;

/**
 * Search plugins allow data from OpenTSDB to be published to a search indexer.
 * Many great products already exist for searching so it doesn't make sense to
 * re-implement an engine within OpenTSDB. Likewise, going directly to the 
 * storage system for searching isn't efficient. 
 * 
 * @note Implementations must have a parameterless constructor. The 
 * {@link #initialize()} method will be called immediately after the plugin is
 * instantiated and before any other methods are called.
 * 
 * @note Since canonical information is stored in the underlying OpenTSDB 
 * database, the same document may be re-indexed more than once. This may happen
 * if someone runs a full re-indexing thread to make sure the search engine is
 * up to date, particularly after a TSD crash where some data may not have been
 * sent. Be sure to account for that when indexing. Each object has a way to 
 * uniquely identify it, see the method notes below.
 * 
 * @warn All indexing methods should be performed asynchronously. You may want
 * to create a queue in the implementation to store data until you can ship it
 * off to the service. Every indexing method should return as quickly as 
 * possible.
 * 
 * @since 2.0
 */
public abstract class SearchPlugin {

  /**
   * Called by TSDB to initialize the plugin
   * 
   * Implementations are responsible for setting up any IO they need as well
   * as starting any required background threads
   * @param tsdb The parent TSDB object
   * @return True if successful, false if initialization failed
   * @throws ?
   */
  public abstract Deferred<Object> initialize(final TSDB tsdb);
  
  /**
   * Called to gracefully shutdown the plugin. Implementations should close 
   * any IO they have open
   * @return ?
   */
  public abstract Deferred<Object> shutdown();
  
  /**
   * Indexes a timeseries metadata object in the search engine
   * @note Unique Document ID = TSUID 
   * @param meta The TSMeta to index
   * @return ?
   */
  public abstract Deferred<Object> indexTSMeta(final TSMeta meta);
  
  /**
   * Indexes a UID metadata object for a metric, tagk or tagv
   * @note Unique Document ID = UID and the Type
   * @param meta The UIDMeta to index
   * @return ?
   */
  public abstract Deferred<Object> indexUIDMeta(final UIDMeta meta);
  
  /**
   * Indexes an annotation
   * @note Unique Document ID = TSUID and start_time. If the TSUID is empty, 
   * this is a global annotation.
   * @param note The annotation to index
   * @return ?
   */
  public abstract Deferred<Object> indexAnnotation(final Annotation note);
  
  /**
   * Executes a simple, text based query against the search engine and returns
   * results
   * @param query The query as generated by a user
   * @return The same query with results filled in
   */
  public abstract Deferred<SearchQuery> executeQuery(final SearchQuery query);
}
