#!/bin/sh
set -e

if [ -x "/etc/init.d/opentsdb-tsd" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d opentsdb-tsd stop || true
	else
		/etc/init.d/opentsdb-tsd stop || true
	fi
fi