// This file is part of OpenTSDB.
// Copyright (C) 2012  The OpenTSDB Authors.
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.  This program is distributed in the hope that it
// will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser
// General Public License for more details.  You should have received a copy
// of the GNU Lesser General Public License along with this program.  If not,
// see <http://www.gnu.org/licenses/>.
package net.opentsdb.core;

import java.io.IOException;

import net.opentsdb.storage.TsdbStore;

import org.codehaus.jackson.map.ObjectMapper;
import org.codehaus.jackson.type.TypeReference;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class will help with all JSON related behavior such as parsing or
 * creating JSON strings. It's to help cut down on code repetition such as
 * catching Jackson errors, etc.
 * NOTE: this class is not thread safe, so only use it in the same thread
 * that where you create it.
 */
public class JSON {
  /** Logging object for this class */
  protected static final Logger LOG = LoggerFactory.getLogger(JSON.class);

  /**
   * Jackson serializer This is public so that other JSON dependencies can use
   * it
   */
  protected static ObjectMapper JsonMapper = new ObjectMapper();

  /**
   * an object that the serializer will convert into a string OR the
   * deserializer will use for type conversion
   */
  protected Object object = null;

  /** Holds any error messages generated by the mapper */
  protected String error = null;

  /**
   * Default constructor
   */
  public JSON() {
  }

  /**
   * Constructor that assigns the local object with whatever you pass as a
   * parameter
   * @param o An object to serialize or the type to deserialize
   */
  public JSON(Object o) {
    object = o;
  }

  /**
   * Attempts to parse the provided JSON string using the class that was passed
   * to the constructor. NOTE: The an object must have been provided via the
   * constructor or this method will log an error and return false
   * @param json A JSON formatted string to deserialize
   * @return True if deserialization was successful (no errors encountered) or
   *         false if there was an error. Check the error string via
   *         {@link getError} to find out what went wrong
   */
  public final boolean parseObject(final String json) {
    // try parsing
    try {
      error = "";   // reset error if one existed
      object = JsonMapper.readValue(json, object.getClass());
      return true;
    } catch (Exception e) {
      error = "Failed to parse JSON: " + e.getMessage();
      LOG.error(error);
      LOG.trace(json);
    }
    return false;
  }
  
  /**
   * Attempts to parse the provided JSON string using the class that was passed
   * to the constructor. NOTE: The an object must have been provided via the
   * constructor or this method will log an error and return false
   * @param json A JSON formatted array of bytes to deserialize
   * @return True if deserialization was successful (no errors encountered) or
   *         false if there was an error. Check the error string via
   *         {@link getError} to find out what went wrong
   */
  public final boolean parseObject(final byte[] json) {
    // try parsing
    try {
      error = "";   // reset error if one existed
      object = JsonMapper.readValue(json, object.getClass());
      return true;
    } catch (Exception e) {
      error = "Failed to parse JSON: " + e.getMessage();
      LOG.error(error);
      LOG.trace(TsdbStore.fromBytes(json));
    }
    return false;
  }

  /**
   * Attempts to parse the provided JSON string using a provided type reference.
   * @param json A JSON formatted string to deserialize
   * @param type The type of object to load into
   * @return True if deserialization was successful (no errors encountered) or
   *         false if there was an error. Check the error string via
   *         {@link getError} to find out what went wrong
   */
  public final boolean parseObject(final String json,
      final TypeReference<?> type) {
    // try parsing
    try {
      error = "";
      object = JsonMapper.readValue(json, type);
      return true;

    } catch (Exception e) {
      error = "Failed to parse JSON: " + e.getMessage();
      LOG.error(error);
      LOG.trace(json);
    }
    return false;
  }
  
  /**
   * Attempts to parse the provided JSON string using a provided type reference.
   * @param json A JSON formatted byte array to deserialize
   * @param type The type of object to load into
   * @return True if deserialization was successful (no errors encountered) or
   *         false if there was an error. Check the error string via
   *         {@link getError} to find out what went wrong
   */
  public final boolean parseObject(final byte[] json,
      final TypeReference<?> type) {
    // try parsing
    try {
      error = "";
      object = JsonMapper.readValue(json, type);
      return true;

    } catch (Exception e) {
      error = "Failed to parse JSON: " + e.getMessage();
      LOG.error(error);
      LOG.trace(TsdbStore.fromBytes(json));
    }
    return false;
  }

  /**
   * Returns a JSON formatted string of the Object provided in the constructor.
   * @return A JSON formatted string if successful, an empty string if there was
   *         an error. Check {@link getError} to find out what went wrong
   */
  public final String getJsonString() {
    if (object == null) {
      error = "TSD Error: The object was null";
      return "";
    }

    try {
      error = "";
      return JsonMapper.writeValueAsString(object);
    } catch (IOException e) {
      error = "Unable to serialize object to JSON: " + e.getMessage();
      LOG.error(error);
    }
    return "";
  }
  
  /**
   * Returns the JSON data as a byte array, useful for passing directly to storage
   * @return A byte array of JSON data if successful, null if there was an error.
   *         Check {@link getError} to find out what went wrong
   */
  public final byte[] getJsonBytes() {
    if (object == null) {
      error = "TSD Error: The object was null";
      return null;
    }

    try {
      error = "";
      return JsonMapper.writeValueAsBytes(object);
    } catch (IOException e) {
      error = "Unable to serialize object to JSON: " + e.getMessage();
      LOG.error(error);
    }
    return null;
  }

  /** Gets the error string */
  public final String getError() {
    return error;
  }

  /** Gets the object */
  public final Object getObject() {
    return object;
  }

  /** Lets other classes access the mapper directly */
  public static ObjectMapper getMapper(){
    return JsonMapper;
  }
}
